version: "3.8"

services:
  backend:
    build: .
    container_name: crow_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Override or add any environment variables here if needed
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: postgres
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      - postgres
      - dynamodb-local

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  postgres_data:
  dynamodb_data:
